### ISSUE TITLE
Incorrect Region setting

### ISSUE THREAD

**Issue by xssChauhan** [yunojuno/django-s3-upload#26]
The repo readme lists `S3DIRECT_REGION` as the setting for setting the region. 
Whereas the the region is read from `S3UPLOAD_REGION` [here](https://github.com/yunojuno/django-s3-upload/blob/master/s3upload/utils.py#L59)

` region = getattr(settings, 'S3UPLOAD_REGION', None)`

**Comment by thealscott** [comment]
fixed by #31
