### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by hugorodgerbrown** [yunojuno/django-s3-upload#3]
Instead of producing 5 min links on each page refresh, it would be nice to have a download button (not a link) that combines the generation of the link and the download in one. That would also give us better tracking on the generation of the links.

Use case: view a page with a downloadable document on it.

- click on button
- retrieve one use link (or 10sec link - something v. restrictive)
- redirect (302) to download file

**Comment by stevejalim** [comment]
Isn't this what the signing view that I added to YJ core does? Could prob be lifted

**Comment by rossmiller** [comment]
@stevejalim we already lifted your (very nice) logic. What @hugorodgerbrown is suggesting can probably make use of the same or similar on the backend.

**Comment by hugorodgerbrown** [comment]
This is also linked to #5 - as auditing people downloading files (or at least asking for a download link) is only possible if we are generating the links just-in-time.
