### ISSUE TITLE
Django2 path in documentation

### ISSUE THREAD

**Issue by HashRocketSyntax** [yunojuno/django-s3-upload#32]
Hi there. Stepping through the documentation. 

Should this:
`url(r'^s3upload/', include('s3upload.urls')),`

Become this?
`path('s3upload/', include('s3upload.urls')),`

**Comment by HashRocketSyntax** [comment]
Hmm. Now getting this error `profile-pic-form/ ^get_upload_params/ [name='s3upload']`

**Comment by HashRocketSyntax** [comment]
Hmm. Now getting this error:

```
Django tried these URL patterns, in this order:

[name='homepage']
profile-pic-form/ ^get_upload_params/ [name='s3upload']
```

**Comment by djm** [comment]
Hi @HashRocketSyntax,

We're on Django 2.0 and use the first version you posted.

I'm afraid we can only offer support in terms of bugs and not Django/installation support so I'm going to close this issue. 

I hope you got/get it working!
Darian

**Comment by shacker** [comment]
@djm What he means is that the syntax `url(` is no longer supported in Django. You must use `path(`

**Comment by djm** [comment]
@shacker Thanks, fixed in https://github.com/yunojuno/django-s3-upload/commit/e9d4dba7a653378e90f312034f0bd29acdfbbcb5
