### ISSUE TITLE
Readme is broken on Pypi

### ISSUE THREAD

**Issue by rhenter** [yunojuno/django-s3-upload#35]
Probably you have to fix a few tags on your document to be a valid MD document. 
use md2html/markdonw2html to check when you finish
![screenshot from 2019-03-08 12-03-23](https://user-images.githubusercontent.com/2206875/54036372-3e72f100-419a-11e9-8ef6-af30b8df7805.png)

**Comment by hugorodgerbrown** [comment]
Unfortunately PyPI doesn't support markdown, so the readme needs converting
to .rst.

**Comment by rhenter** [comment]
I can help you. I’ll create a pull request latter.

All the best,

Rafael Henter
Cel: +55 24 99275-5167


Em 9 de mar de 2019, à(s) 11:58, Hugo Rodger-Brown <notifications@github.com> escreveu:

> Unfortunately PyPI doesn't support markdown, so the readme needs converting
> to .rst.
> 
>

**Comment by rhenter** [comment]
Done. 

https://github.com/yunojuno/django-s3-upload/pull/36

**Comment by djm** [comment]
Closing as PyPI supports markdown now.
