### ISSUE TITLE
Inlines not working correctly on Chrome >= 127

### ISSUE THREAD

**Issue by tomeyro** [yunojuno/django-s3-upload#45]
`DOMNodeInserted` events are no longer supported in `Chrome >= 127`, so new lines added to Inlines are not properly detected and upload fields are not initialized.

![image](https://github.com/user-attachments/assets/3b5c44b6-59f6-4459-ba3b-6a1cce7a4dc7)

Affected code:

https://github.com/yunojuno/django-s3-upload/blob/master/s3upload/static/s3upload/js/django-s3-uploads.js#L692-L698

**Comment by sahilasopa** [comment]
@culshaw was a release supposed to be created for the update pushed? the latest version in pip does not fix this bug
